- name: postfix
  import_tasks: postfix.yml
  tags: postfix

- name: dovecot
  import_tasks: dovecot.yml
  tags: dovecot

- name: rspamd
  import_tasks: rspamd.yml
  tags: rspamd

#- include: spamassassin.yml
#  tags: spamassassin

- name: solr
  import_tasks: solr.yml
  tags: solr

- name: checkrbl
  import_tasks: checkrbl.yml
  tags: checkrbl

#- name: zpush
#  import_tasks: z-push.yml
#  tags: zpush

- name: autoconfig
  import_tasks: autoconfig.yml
  tags: autoconfig

- name: mailmain
  import_tasks: mailman.yml
  tags: mailman
