---
- name: Update apt cache
  apt: update_cache=yes
  tags:
    - dependencies

- name: Upgrade all safe packages
  apt: upgrade=safe
  tags:
    - dependencies

- name: Install necessities and nice-to-haves
  package:
    state: latest
    name:
      - apache2
      - apache2-data
      - apache2-bin
      - apache2-utils
      - apt-transport-https
      - apticron
      - build-essential
      - debian-goodies
      - git
      - htop
      - iftop
      - iotop
      - molly-guard
      - mosh
      - python3-software-properties
      - ruby
      - screen
      - sudo
      - unattended-upgrades
      - vim
      - zsh
  tags:
    - dependencies

- name: timezone - configure /etc/timezone
  copy:
    content: "{{ common_timezone | regex_replace('$', '\n') }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
  register: common_timezone_config

- name: timezone - Set localtime to UTC
  file: src=/usr/share/zoneinfo/Etc/UTC dest=/etc/localtime
  when: common_timezone_config.changed

- name: timezone - reconfigure tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata
  when: common_timezone_config.changed

- name: Apticron email configuration
  template: src=apticron.conf.j2 dest=/etc/apticron/apticron.conf

- name: Create decrypted directory (even if encfs isn't used)
  file: state=directory path=/decrypted

- name: Set decrypted directory permissions
  file: state=directory path=/decrypted group=mail mode=0775

- name: Ensure locale en_US.UTF-8 locale is present
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: encfs
  import_tasks: encfs.yml
  tags: [ encfs ]
  when: false

- name: Users
  import_tasks: users.yml
  tags: [ users ]

- name: Apache
  import_tasks: apache.yml
  tags: [ apache ]

- name: ssl
  import_tasks: ssl.yml
  tags: [ ssl ]

- name: Letsencrypt
  import_tasks: letsencrypt.yml
  tags: [ letsencrypt ]

- name: ufw
  import_tasks: ufw.yml
  tags: [ ufw ]

- name: security
  import_tasks: security.yml
  tags: [ security ]

- name: ntp
  import_tasks: ntp.yml
  tags: [ ntp ]

- name: google_auth
  import_tasks: google_auth.yml
  tags: [ google_auth ]

- name: postgres
  import_tasks: postgres.yml
